version: '3.4'

services:
    seleniumchromedriver:
        image: selenium/standalone-chrome
        ports: 
            - "4444:4444"        
    uitests:
        image: uitests
        build:
            context: .
            dockerfile: dockerfile    
        entrypoint:
            - dotnet
            - test
            - "UITests.csproj"